language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"
matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
env:
  global:
    - secure: "iSsrrG5EKZU+D6vlzkYodOmDg7KJfkRHtww07LlkOnErGfa+x/GVP19MlKVu1ER56MxOl54DaSONCPie+Iv+U9esQClNyWaPL75dRjwfUJGqqQ/yQG6e8hX4wz2zmqbDWyD4JwDjCE0qCSqOfEcWaSZjqqoy/fq0TOPKHRnemm5jNIyFxLFiCEVplLuNePrWR+w15NvB3g8n6IY7rDONvhq67EatPiwPp+Ut7KsuAdAJT+ldEdefLD8bfI+nenqxnflyKlvJwsRJSUAlvJK9nqOVbX3LR2BodUWTLb+Wxu7mnVuDeRYjE/cT7PHdOx/hOpcVxTrJCFAswFlBCeiLG1zC/dST52eQKRWDP5HU0cO26oi+cCXfk4lpOBj71UY+XryODbofQLGJMlrmKPPS/ChG6izPySWKqFnGSjnp8IFdadItEQeADId665E0JoNyfal3LmqMl+BQBGdyr6SjTwRnQXtQjgLflK67Oaptup5ribtpJ0gMTpYLajfIbCS5UehrLCGfhs0kszITBCIMGw18kIbw61eGKRRM3ivhGjRGBa+Z9UYJsfkYvWx+rOJpxbcHMvMFX7+kD9IMAgPFNY9H010UtqDzANFhNhAZ4PYM7A+G2GxoZkgH51qoaw/vzI5zZ6LnPd3z3RYiBN60XWPilms3vNSfr1kpIJsA/1g="
    - secure: "EzO5mmB30Vg0/n/UkjDmE5Wyf8SnEmbhODrOlue33d/Kn97dFf/YUZnmhgRcPnbBofjti6nuM9nxsrs0dm5VcmXgYvVV8LuFmxtfTwc6pz7Z/YZ0PUL1LigRKUq1OoDrK1utWYsSUjyGTpZ3nwobdtFxuSriFepV1M7NS3xVWrzJKgU02iYf64rMzF9vmp23DJE5J7fp054Axmd+qJj73/G6uts52RVerTzFgkitgRFaOIsKwqypcmD2AkvVA5xVodrGzJ8RemXYVMfoorrxmEYVWowNGNxur0uWQYro6Bza6Fr0H8yyAiSEtYL4mYFXn08vnxxepKutKtYoSjDpDQF3G7lvkMT3SkFZD+2y78RnsGZWsqX4FXPJlQjJFGlMLScz6XETxSEVrk0Dv/CBd1umo65OTYLdfBczhQCT8x3ZKBCrovJZeuoEQUnOUhY/ENmpbOsTq/a6GMR9W3a4DvpIcf+de8fHFOVHY/phDOsyyyRO3SD46fLCAZWrrWVT9hTzHTTvsHMAH0Tnoy3DLaoCkNyhhlx9KvhvJZyr3K1BlMy6KZnfF89bTMjW2VHTMD1NKUEKUwaZFdDcgmInJKNlpbDDaixnttPwKWk4uRfoS9dkfnDR4KDya9ISenhjc39f06L61eqL7/fJF1iyHYIcGXHquS1Q38A38/4sgWk="
before_install:
  - pip install poetry
  - pip install codecov
install:
  - poetry install
script:
  - poetry run pytest --cov
after_success:
  - codecov
before_deploy:
  - poetry build
deploy:
  provider: script
  script: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
    python: 3.7
