language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
script:
  - py.test --cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
