language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
branches:
  only:
    - master
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
