language: python
python:
    - "3.4"
    - "3.5"
    - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - py.test --cov .\ipfromwebpage_tests.py
after-success:
  - coveralls
