version: 2.1

orbs:
  python: circleci/python@3.3.0

jobs:
  build-and-test:
    parameters:
      python-version:
        type: string
    executor: 
      name: python/default
      tag: << parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          command: |
            uv run pytest --cov
  pypi_publish:
    executor: 
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          command: |
            uv build && uv publish -u $PYPI_USERNAME -p $PYPI_PASSWORD

workflows:
  main:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      - pypi_publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

